version: "3.1"

services:
  database:
    image: mariadb:10.4.10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: react-project
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - 8090:80
    networks:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root

  api:
    image: node:latest
    restart: always
    working_dir: /home/app
    volumes:
      - ./server:/home/app
    command: npm run start
    environment:
      DB_HOST: database
      DB_USER: 'user'
      DB_PASSWORD: 'user'
      DB_NAME: 'react-project'
    networks:
      - database
      - front
    ports:
      - 8080:8080

  front:
    image: node:alpine
    environment:
      API_BREAKPOINT: "https://localhost:8080"
    working_dir: /home/app
    volumes:
      - ./front:/home/app
    command: npm run start
    ports:
      - 80:3000
    networks:
      - front

networks:
  database:
  front:
